version: "3.5"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto:/mosquittoconf
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.mosquitto-websocket.rule=Host(`mqtt.${DOMAIN:-gregstretton.org}`)"
      - "traefik.http.routers.mosquitto-websocket.entrypoints=websecure"
      - "traefik.http.routers.mosquitto-websocket.tls=true"
      - "traefik.http.routers.mosquitto-websocket.tls.certresolver=myresolver"

      # Add a service for WebSocket traffic
      - "traefik.http.services.mosquitto-websocket.loadbalancer.server.port=9001"

       # TCP Router for MQTT
      - "traefik.tcp.routers.mqtt-router.rule=HostSNI(`mqtt.${DOMAIN:-gregstretton.org}`)"
      - "traefik.tcp.routers.mqtt-router.entrypoints=mqttsecure"
      - "traefik.tcp.routers.mqtt-router.tls=true"
      - "traefik.tcp.routers.mqtt-router.tls.certresolver=myresolver"
      - "traefik.tcp.routers.mqtt-router.service=mosquitto"
      - "traefik.tcp.services.mosquitto.loadbalancer.server.port=1883"
  interface:
    image: gkstretton/asol-dev-interface:latest
    ports:
      - 8085:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asol-dev-interface.rule=Host(`asol.${DOMAIN:-gregstretton.org}`)"
      - "traefik.http.routers.asol-dev-interface.entrypoints=web,websecure"
      - "traefik.http.routers.asol-dev-interface.tls=true"
      - "traefik.http.routers.asol-dev-interface.tls.certresolver=myresolver"
    networks:
      - traefik

  # port 8889 is port forwarded so this is served directly rather than through
  # traefik. I couldn't get traefik to work with webrtc, maybe a NAT type issue.
  # This is a proxy instance that is accessed through webrtc. internally it
  # calls the instance on DEPTH through RTSP over port 8554. This connection to
  # DEPTH is over a reverse ssh tunnel initiated by systemd job sshtunnel.service
  # on DEPTH.
  # note that the TLS cert automation is not set up so will expire early August 2023
  mediamtx:
    image: aler9/rtsp-simple-server
    restart: unless-stopped
    # networks:
      # - traefik
    network_mode: "host"
    ports:
      - 8889:8889
    volumes:
      - ./mediamtx/mediamtx.yml:/rtsp-simple-server.yml
      - ./mediamtx/server.key:/server.key
      - ./mediamtx/server.crt:/server.crt
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.tcp.routers.webrtc-websocket.rule=HostSNI(`webrtc.${DOMAIN:-gregstretton.org}`)"
    #   - "traefik.tcp.routers.webrtc-websocket.entrypoints=webrtc"
    #   - "traefik.tcp.routers.webrtc-websocket.tls=true"
    #   - "traefik.tcp.routers.webrtc-websocket.tls.certresolver=myresolver"
    #   - "traefik.tcp.routers.webrtc-websocket.service=mediamtx"
    #   - "traefik.tcp.services.mediamtx.loadbalancer.server.port=8889"

networks:
  traefik:
    name: traefik_network